TebLocalPlannerROS:

  odom_topic: Odometry

  # Trajectory

  teb_autosize: True
  dt_ref: 0.2
  dt_hysteresis: 0.02
  max_samples: 500
  global_plan_overwrite_orientation: False
  allow_init_with_backwards_motion: False # before False 是否允许倒车
  max_global_plan_lookahead_dist: 1.0
  global_plan_viapoint_sep: 0.3
  global_plan_prune_distance: 4.0
  exact_arc_length: False
  feasibility_check_no_poses: 3
  publish_feedback: False

  # Robot
  max_vel_x: 1.5 # before 1.2
  max_vel_x_backwards: 0.5 # before 0.01
  # allow_backward_motion: false # 禁止向后运动
  max_vel_theta: 6.28 # before 0.8
  acc_lim_x: 3.0 # before 3.0
  acc_lim_theta: 12.56 # before 3.0
  min_turning_radius: 0.0 # diff-drive robot (can turn on place!)

  footprint_model:
    type: "polygon"    #多边形
    vertices: [ [ -0.4, -0.4 ], [ -0.4, 0.4 ], [ 0.4, 0.4 ], [ 0.4, -0.4 ] ]


  #*******************************************************************************
  # GoalTolerance

  xy_goal_tolerance: 1.0 # before 0.1
  yaw_goal_tolerance: 3.14159
  free_goal_vel: True
  complete_global_plan: True

  cmd_angle_instead_rotvel: False
  wheelbase: 0.0

  # Obstacles
  min_obstacle_dist: 0.5 #This value must also include our robot radius, since footprint_model is set to "point".
  inflation_dist: 0.5
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.5
  obstacle_poses_affected: 15

  dynamic_obstacle_inflation_dist: 0.6
  include_dynamic_obstacles: True

  costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  obstacle_cost_exponent: 4
  weight_max_vel_x: 20
  weight_max_vel_theta: 1
  weight_acc_lim_x: 10
  weight_acc_lim_theta: 10
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 100  # 10000(zzh)
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 3 # must be > 0 before 8
  weight_shortest_path: 0
  weight_obstacle: 1000 # 100(zzh)
  weight_inflation: 100
  weight_dynamic_obstacle: 50
  weight_dynamic_obstacle_inflation: 10
  weight_viapoint: 1 # before 100
  weight_adapt_factor: 2

  # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  max_number_classes: 2
  selection_cost_hysteresis: 1.0
  selection_prefer_initial_plan: 0.9
  selection_obst_cost_scale: 100.0
  selection_alternative_time_cost: False

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  roadmap_graph_area_length_scale: 1.0
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  switching_blocking_period: 0.0
  viapoints_all_candidates: True
  delete_detours_backwards: True
  max_ratio_detours_duration_best_duration: 3.0
  visualize_hc_graph: False
  visualize_with_time_as_z_axis_scale: False

  # Recovery

  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 2 # 卡住多少秒后的恢复 before 10
  oscillation_filter_duration: 2 # before 10

  recovery_behavior_enabled: true
  recovery_behaviors:
  # - name: slow_and_clear
  #   type: "move_slow_and_clear/MoveSlowAndClear"
  - name: clear_costmap
    type: "clear_costmap_recovery/ClearCostmapRecovery"
    # 解决雷达噪点
