controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  chassis_controller:
    type: sct_chassis_controller/Controller
    timeout: 0.1
    max_acc_x: 5.0
    max_acc_w: 30.0
